int ft_strlen(char *s);
void ft_strcpy(char *dest, char *src);
void	check_quote(char c, char *bitflag_quote);
void	check_quote2(char c, char *bitflag_quote);
int find_bracket(char *s);
char *newstrcat(char *s1, char *s2);
int bracket_num(char *s);
int is_blank(char c);
int is_next_curly_bracket(int fd);
int is_func_dec(char *s, int fd);
void write_to_header(int fd, char *s);
int is_same_extension(char *s, char *extension);
void	ft_qsort(unsigned long long int *array,
		int left, int right);
unsigned long long int ft_pow(unsigned long long int base, int n);
unsigned long long int str2long(char *s);
char *extract_func_name(char *s);
int input_existing_func(char *argv, unsigned long long int *func_name);
int nibun_find(unsigned long long int *array, int num, unsigned long long int n);
int is_func_existing(unsigned long long int *func_name, int func_num, char *s);
void process_main(unsigned long long int *func_name, int func_num, int fd_read, int fd_write);
int ini_func_name(unsigned long long int *func_name);
int is_generated_h(char *s);
int some_args(int argc, char *argv[]);
void no_args(int argc);
int main(int argc, char *argv[]);
int func(void);
